CREATE TABLE app_user (
    id UUID PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    enabled BOOLEAN NOT NULL,
    first_login_at TIMESTAMP WITH TIME ZONE,
    last_login_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(100) NOT NULL UNIQUE,
    enabled BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE permission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(100) NOT NULL UNIQUE,
    enabled BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE user_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES app_user(id),
    role_id BIGINT NOT NULL REFERENCES role(id),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_user_role UNIQUE (user_id, role_id)
);

CREATE TABLE role_permission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id BIGINT NOT NULL REFERENCES role(id),
    permission_id BIGINT NOT NULL REFERENCES permission(id),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_role_permission UNIQUE (role_id, permission_id)
);

CREATE TABLE auth_session (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES app_user(id),
    status VARCHAR(30) NOT NULL,
    revoke_reason VARCHAR(50),
    login_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    last_activity_at TIMESTAMP WITH TIME ZONE NOT NULL,
    logout_at TIMESTAMP WITH TIME ZONE,
    ip_address VARCHAR(64),
    user_agent VARCHAR(500),
    current_access_token_jti UUID,
    access_token_expires_at TIMESTAMP WITH TIME ZONE,
    version BIGINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_auth_session_user_status ON auth_session(user_id, status);

CREATE TABLE refresh_token (
    id UUID PRIMARY KEY,
    session_id UUID NOT NULL REFERENCES auth_session(id),
    family_id UUID NOT NULL,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    used_at TIMESTAMP WITH TIME ZONE,
    revoked_at TIMESTAMP WITH TIME ZONE,
    replaced_by_token_id UUID
);

CREATE INDEX idx_refresh_token_session ON refresh_token(session_id);
CREATE INDEX idx_refresh_token_family ON refresh_token(family_id);

CREATE TABLE api_client (
    id UUID PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    client_type VARCHAR(30) NOT NULL,
    client_key VARCHAR(150) NOT NULL UNIQUE,
    secret_hash VARCHAR(255) NOT NULL,
    enabled BOOLEAN NOT NULL,
    current_user_required BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE api_client_authority (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id UUID NOT NULL REFERENCES api_client(id),
    authority VARCHAR(150) NOT NULL,
    CONSTRAINT uq_api_client_authority UNIQUE (client_id, authority)
);

CREATE TABLE security_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(80) NOT NULL,
    principal VARCHAR(150),
    session_id UUID,
    detail VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE customer_order (
    id UUID PRIMARY KEY,
    customer_id UUID,
    description VARCHAR(500) NOT NULL,
    status VARCHAR(30) NOT NULL,
    created_by VARCHAR(150) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
