CREATE TABLE login_throttle (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    throttle_key VARCHAR(250) NOT NULL,
    attempted_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_login_throttle_key ON login_throttle(throttle_key);
CREATE INDEX idx_login_throttle_attempted_at ON login_throttle(attempted_at);