ALTER TABLE api_client ADD COLUMN signing_secret VARCHAR(255);

CREATE TABLE api_client_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id UUID NOT NULL REFERENCES api_client(id),
    user_id UUID NOT NULL REFERENCES app_user(id),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_api_client_user UNIQUE (client_id, user_id)
);

CREATE INDEX idx_api_client_user_user ON api_client_user(user_id);